dist: trusty
language: go

# Only current version is considered given limitations to publish more than one
# report per build to Quality Gates.
go:
  - "1.11"

# This build should not be triggered by tags
if: tags IS blank

# Anything in install that returns a nonzero exit code will
# flunk the build and immediately stop. It's sorta like having
# set -e enabled in bash.
install:
  # run the initial setup
  - make setup
  # Export the current branch according to travis (including pr builds) 
  - export BUILD_BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)

# script always run to completion (set +e). All of these code checks are must haves
# in a modern Go project.
script:
  # Generate coverage and checkstyle report
  - make test
  - make docker-build

after_failure:
  - reports-publisher

after_success:
  - reports-publisher

deploy:
  - provider: script
    script: make docker-publish
    on:
      all_branches: true

notifications:
  webhooks:
    - https://devhose.spt-engprod-pro.schibsted.io/devhose/travis
