# Default values for trans.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: containers.mpi-internal.com/yapo/trans
  tag: "20190813_215755" # Should it pass from the command line
  pullPolicy: IfNotPresent
  pullSecret: containers-mpi-internal-com

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

newrelic:
  enabled: "false"

trans:
  commands: "transinfo|get_account|newad|clear|loadad|set_ad_evaluation|bump_target_advertisement"
  host: "172.21.10.62"
  port: "5656"

prometeus:
  enabled: "true"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: "trans.dobosi-norbert.yapo.cl" # Should it pass from the command line
      paths: ['/']
