{
 "title": "Trans Service",
 "description": "$DESCRIPTION",
 "tags": [
  "golang",
  "rancher",
  "docker",
  "service"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "STACK_NAME", "label": "stack_name", "query": "ana-mora" },
   { "name": "SERVICE_NAME", "label": "service_name", "query": "trans" },
   {
    "name": "INSTANCE",
    "label": "Instance",
    "query": "query_result(sum({kubernetes_name=\"$SERVICE_NAME\"})by(instance))"
   },
   {
    "name": "PERIOD",
    "label": "Period",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "GO_VERSION",
    "query": "go_info{instance=\"$INSTANCE\"}"
   },
   { "name": "DESCRIPTION", "query": "Trans service" },
   {
    "name": "GITHUB_LINK",
    "query": "https://github.mpi-internal.com/Yapo/trans"
   },
   { "name": "EVENTS_COLLECTOR_METRIC_NAME", "query": "trans_service_events_total" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "content": "<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\n\n<div class=\"card\">\n  <img src=\"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Gopher-ru.png/768px-Gopher-ru.png\" alt=\"logo\" style=\"width:70px\">\n\n  <!-- Service name -->\n\n  <h1> <span style=\"text-transform:capitalize;\">$SERVICE_NAME<span> Service </h1>\n\n  <!-- give a description -->\n  <p class=\"title\"> Using $GO_VERSION </p>\n\n  \n  <!-- give a description -->\n  <p> $DESCRIPTION </p>\n  <!-- add link to your repository -->\n  <p><a href=\"$GITHUB_LINK\"><button>Github <i class=\"fa fa-github\"></i> </button></a></p>\n</div>\n\n\n<!--style -->\n<style>\n.card {\n  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);\n  max-width: 300px;\n  margin: auto;\n  text-align: center;\n}\n\n.card .title {\n  color: grey;\n  font-size: 18px;\n}\n\n.card button {\n  border: none;\n  outline: 0;\n  display: inline-block;\n  padding: 8px;\n  color: white;\n  background-color: #000;\n  text-align: center;\n  cursor: pointer;\n  width: 100%;\n  font-size: 18px;\n}\n\n.card a {\n  text-decoration: none;\n  font-size: 22px;\n  color: black;\n}\n\n.card button:hover, a:hover {\n  opacity: 0.7;\n}\n</style>"
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "timestamp(process_start_time_seconds{instance=\"$INSTANCE\"})\n-\nprocess_start_time_seconds{instance=\"$INSTANCE\"}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 10, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{instance=\"$INSTANCE\"}[$PERIOD])",
     "legendFormat": "{{stack_name}}.{{service_name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"$INSTANCE\"}+process_virtual_memory_bytes{instance=\"$INSTANCE\"}",
     "legendFormat": "Memory used"
    },
    {
     "expr": "process_virtual_memory_bytes{instance=\"$INSTANCE\"}",
     "legendFormat": "Virtual"
    },
    {
     "expr": "process_resident_memory_bytes{instance=\"$INSTANCE\"}",
     "legendFormat": "Resident"
    },
    {
     "expr": "go_memstats_alloc_bytes{instance=\"$INSTANCE\"}",
     "legendFormat": "Allocated"
    }
   ]
  },
  {
   "title": "Max FDS",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_max_fds{instance=\"$INSTANCE\"}"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 4 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{instance=\"$INSTANCE\"}+\nprocess_virtual_memory_bytes{instance=\"$INSTANCE\"})"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{instance=\"$INSTANCE\"}",
     "legendFormat": "Routines "
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(container_network_transmit_bytes_total{container_label_appname=\"$SERVICE_NAME\"}[$PERIOD])",
     "legendFormat": "OUT"
    },
    {
     "expr": "increase(container_network_receive_bytes_total{container_label_appname=\"$SERVICE_NAME\"}[$PERIOD])",
     "legendFormat": "IN"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{instance=\"$INSTANCE\"} ",
     "legendFormat": "Current_FDS"
    }
   ]
  },
  {
   "title": "Requests Counters",
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "api_requests_total{instance=\"$INSTANCE\"}\n"
    }
   ]
  },
  {
   "title": "Requests made in $PERIOD period",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 7, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(api_requests_total{instance=\"$INSTANCE\"}[$PERIOD])",
     "legendFormat": "{{code}} [{{method}}] {{handler}}"
    }
   ]
  },
  {
   "title": "Request duration - Rate $PERIOD",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(request_duration_seconds_sum{instance=\"$INSTANCE\"}[$PERIOD])\n/rate(request_duration_seconds_count{instance=\"$INSTANCE\"}[$PERIOD])\n",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 12 },
   "content": "\n<div class=\"info-table\"> \n<center><strong>Endpoints description</strong></center> \n\n<table>\n  <tr>\n    <td>/endpoint1 </td>\n    <td>v1 put a description here</td>\n  </tr>\n    <tr>\n    <td>/endpoint2 </td>\n    <td>v2 put a description here</td>\n  </tr>\n</table>\n</div>\n\n\n<style>\n.info-table td {\n  border: 0.1px solid gray;\n}\n</style>"
  },
  {
   "title": "Request Size - Rate $PERIOD",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(request_size_bytes_sum{instance=\"$INSTANCE\"}[$PERIOD])\n/ rate(request_size_bytes_count{instance=\"$INSTANCE\"}[$PERIOD])\n\n",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  { "title": "Info & Success Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Info Events Counters",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "$EVENTS_COLLECTOR_METRIC_NAME{instance=\"$INSTANCE\", type=~\"info|success\"}",
     "legendFormat": "{{type}} - {{entity}}.{{event}}"
    }
   ]
  },
  {
   "title": "Info Events in $PERIOD period",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 7, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase($EVENTS_COLLECTOR_METRIC_NAME{instance=\"$INSTANCE\", type=~\"info|success\"}[$PERIOD])\n",
     "legendFormat": "{{type}} - {{entity}}.{{event}}"
    }
   ]
  },
  {
   "title": "Info Events",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "$EVENTS_COLLECTOR_METRIC_NAME{instance=\"$INSTANCE\", type=~\"info|success\"}\n",
     "legendFormat": "{{type}} - {{entity}}.{{event}}"
    }
   ]
  },
  { "title": "Error Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Error Events Counters",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "$EVENTS_COLLECTOR_METRIC_NAME{instance=\"$INSTANCE\", type=~\"error|crit\"}",
     "legendFormat": "ERROR - {{entity}}.{{event}}"
    }
   ]
  },
  {
   "title": "Error Events in $PERIOD period",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 7, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase($EVENTS_COLLECTOR_METRIC_NAME{instance=\"$INSTANCE\", type=~\"error|crit\"}[$PERIOD])\n",
     "legendFormat": "ERROR - {{entity}}.{{event}}"
    }
   ]
  },
  {
   "title": "Error Events",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "$EVENTS_COLLECTOR_METRIC_NAME{instance=\"$INSTANCE\", type=\"error\"}\n",
     "legendFormat": "ERROR - {{entity}}.{{event}}"
    }
   ]
  },
  { "title": "Other events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Error Events Counters",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "$EVENTS_COLLECTOR_METRIC_NAME{instance=\"$INSTANCE\", type!=\"info\", type!=\"success\", type!=\"error\"}",
     "legendFormat": "{{type}} - {{entity}}.{{event}}"
    }
   ]
  },
  {
   "title": "Other Events in $PERIOD period",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 7, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase($EVENTS_COLLECTOR_METRIC_NAME{instance=\"$INSTANCE\", type!=\"error\",type!=\"success\",type!=\"info\"}[$PERIOD])\n",
     "legendFormat": "{{type}} - {{entity}}.{{event}}"
    }
   ]
  },
  {
   "title": "Other Events",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "$EVENTS_COLLECTOR_METRIC_NAME{instance=\"$INSTANCE\", type!=\"error\", type != \"info\"}\n",
     "legendFormat": "{{type}} - {{entity}}.{{event}}"
    }
   ]
  }
 ]
}