FROM alpine:3.8
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*

ARG GIT_COMMIT
ARG GIT_BRANCH
ARG GIT_COMMIT_DATE
ARG BUILD_CREATOR
ARG APPNAME

ENV PS1="\[\e[1;32m\]$APPNAME \[\e[1;31m\][`pwd`] # \[\e[0m\]"
ENV TZ America/Santiago

# Need to define ENV in order to use it in CMD

LABEL branch=$GIT_BRANCH \
   commit=$GIT_COMMIT \
   commit-date=$GIT_COMMIT_DATE \
   build-creator=$BUILD_CREATOR \
   appname=$APPNAME

COPY app.docker /home/user/app/
RUN touch /home/user/app/$GIT_COMMIT

EXPOSE 8080
WORKDIR /home/user/app/

CMD ["./app.docker"]