apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name}}-trans-configmap
  labels:
{{ include "trans.labels" . | indent 4 }}
data:
  NEWRELIC_ENABLED: "{{ .Values.newrelic.enabled }}"
  TRANS_COMMANDS: "{{ .Values.trans.commands }}"
  TRANS_HOST: "{{ .Values.trans.host }}"
  TRANS_PORT: "{{ .Values.trans.port }}"
  PROMETHEUS_ENABLED: "{{ .Values.prometeus.enabled }}"
